debug: true
server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@54.254.209.228:27017/case_service_db?authSource=admin

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem

  rabbitmq:
    host: ${RABBITMQ_HOST:54.254.209.228}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin123}

mongock:
  change-logs-scan-package: com.csm.caseservice.config
